# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["amdgpu"];
  boot.kernelModules = ["kvm-amd" "amdgpu"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fa117561-1f28-401e-807f-188a82709ecc";
    fsType = "btrfs";
    options = ["noatime" "compress=zstd" "space_cache=v2" "subvol=@"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fa117561-1f28-401e-807f-188a82709ecc";
    fsType = "btrfs";
    options = ["noatime" "compress=zstd" "subvol=@home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/fa117561-1f28-401e-807f-188a82709ecc";
    fsType = "btrfs";
    options = ["noatime" "compress=zstd" "subvol=@nix"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/fa117561-1f28-401e-807f-188a82709ecc";
    fsType = "btrfs";
    options = ["noatime" "compress=zstd" "subvol=@persist"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/fa117561-1f28-401e-807f-188a82709ecc";
    fsType = "btrfs";
    options = ["noatime" "compress=zstd" "subvol=@log"];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/8FE3-0588";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/ca3ce5bf-6879-4d79-b37f-b656c4c1c2ca";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
