# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b5447861-d0f9-41d1-8a31-0b2a15741b72";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/b5447861-d0f9-41d1-8a31-0b2a15741b72";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6328-2644";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b5447861-d0f9-41d1-8a31-0b2a15741b72";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b5447861-d0f9-41d1-8a31-0b2a15741b72";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/partition-root" =
    { device = "/dev/disk/by-uuid/b5447861-d0f9-41d1-8a31-0b2a15741b72";
      fsType = "btrfs";
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/b5447861-d0f9-41d1-8a31-0b2a15741b72";
      fsType = "btrfs";
      options = [ "subvol=var/log" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens33.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
